# This is code of composite pattern . Generated by pattern.
# 

class #class_name#
  attr_accessor :name,:parent
  def initialize(name)
  	@name = name
  	@parent = nil
  end
  # TODO: operations
#operations#
end
