# This is code of composite pattern . Generated by pattern.
# 
require "#lc_composite_name#"

class #composite_object_name# < #composite_name#
  def initialize
  	super("#lc_composite_object_name#")
  	#ToDo :add sub class
  	add_sub_task(#sub_class)
  end
  # TODO: operations
#operations#
end
