# This is code of composite pattern . Generated by pattern.
# 
require "#lc_class_name#"

class #leaf_name# < #class_name#
  def initialize
  	super("#leaf_name#")
  end
  # TODO: operations
#operations#
end
